### ISSUE TITLE
Owable.sol missing functionality .

### ISSUE THREAD

**Issue by orenyodfat** [OpenZeppelin/openzeppelin-contracts-ethereum-package#86]
With the latest implementation of Ownable.sol , there is no way straight fwd way to set owner other than the deployer.
https://github.com/OpenZeppelin/openzeppelin-contracts-ethereum-package/blob/master/contracts/access/Ownable.sol#L23 
One need to deploy and then need to transferOwnership from the deployer account.

This is not so optimal pattern , especially , if using the upgradable proxy pattern where the actual deployer..is the a contract which does not provide a way to do that ...[like this](https://github.com/OpenZeppelin/openzeppelin-sdk/blob/master/packages/lib/contracts/application/App.sol#L117)

In the previous implementation of Ownable there was an initilize function which enable that.
`/**
     * @dev Initializes the contract setting the deployer as the initial owner.
     */
    function initialize(address sender) public initializer {
        _owner = sender;
        emit OwnershipTransferred(address(0), _owner);
    }`

**Comment by frangio** [comment]
Hi @orenyodfat. Thank you for reporting.

This has changed from 2.x because we're trying to keep this package as similar as possible to the "vanilla" OpenZeppelin Contracts package, in order to make it easier and less error-prone for us to maintain it, and this was one of the differences. Unfortunately we didn't foresee this issue with `App`.

It is an issue in vanilla Contracts which I have reported in https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2236.

Please take a look over there for the potential workarounds that you can use until we release a fix, and let's continue the discussion over there.
