### ISSUE TITLE
Missing SPDX license identifier warnings

### ISSUE THREAD

**Issue by uniibu** [OpenZeppelin/openzeppelin-contracts-ethereum-package#87]
**🧐 Motivation**
This is in relation to https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2234 and https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2235 

**📝 Details**
As of `Solidity 0.6.8` Solidity issues warnings on all contracts that has no `SPDX license identifier` as shown by the image below.

![image](https://i.gyazo.com/a6f36ca51e47568ae75896030ae5dfab.png)

**Comment by frangio** [comment]
@uniibu I believe this has already been fixed in #2235, right?

**Comment by PaulRBerg** [comment]
I think this is trickier than it seems. https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2235 sets the license to "MIT", but the end-user of the OpenZeppelin library may want to use a different license.

It's also common for Ethereum developers to [flatten](https://github.com/nomiclabs/truffle-flattener) their contracts before going to to mainnet, and with a SPDX predefined by OpenZeppelin, there will be conflicting licenses in the final smart contract product.

Ideally, the Solidity compiler should allow turning off some of its rules if the user annotates it (similar to how eslint makes this possible).

**Comment by frangio** [comment]
@PaulRBerg I agree that this is problematic, but I don't see that OpenZeppelin Contracts is doing anything wrong including the MIT license identifiers. Would you agree?

If a project uses the files we provide as part of their project, my understanding is that it cannot claim a different license for those files. They can use a different license for their own files, however, and in that case I don't know what the SPDX comment should say for the flattened file.

I've created these two issues to discuss and track this:
- https://github.com/ethereum/solidity/issues/8989
- https://github.com/nomiclabs/truffle-flattener/issues/55

I am closing this issue as I believe we have resolved this on our side, but I'm keeping track of the issues linked above so that we can solve the problems this may be causing to users.

**Comment by PaulRBerg** [comment]
Actually yeah you're right. If they do flatten the contracts, they can do a bit of extra work and de-dup the unfit licenses.

**Comment by abcoathup** [comment]
Hi @PaulRBerg,

I posted in the forum about SPDX license identifiers.  

Verification is the big impact, with the likelihood that we need to move away from flattened file verification.
https://forum.openzeppelin.com/t/solidity-0-6-8-introduces-spdx-license-identifiers/2859
